# Direct - Path Shortcuts Configuration
# Use single quotes for Windows paths to avoid backslash escaping issues.

[paths]
autohotkey = 'C:\Users\Khorn Victor\OneDrive\Documents\AutoHotkey'
camcycber = 'C:\Desktop\Student Online (SO)\Camcycber'
config = 'C:\Users\Khorn Victor\.config'
drive = 'C:\Desktop\Drive'
duck = 'C:\Desktop\Rubber Duck'
env = 'C:\Desktop\Student Online (SO)\Code'
etec = 'C:\xampp\htdocs\ETEC'
me = 'C:\Desktop\Me'
mock = 'C:\Desktop\Student Online (SO)\Mock Exam'
obsidian = 'C:\Desktop\Obsidean'
rdtc = 'C:\Desktop\Student Online (SO)\RDTC\aero-service'
stj = 'C:\Desktop\Student Online (SO)\Techno\other\STJ'
techno = 'C:\Desktop\Student Online (SO)\Techno\I3-GIC-A\Semester2'
tool = 'C:\Tool'
